services:
    localstack:
        image: localstack/localstack:4.13.1
        container_name: garage_localstack
        environment:
            - AWS_DEFAULT_REGION=SA-EAST-1
            - EDGE_PORT=4566
            - SERVICES=lambda
        ports:
            - '4566:4566'
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/var/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - garage-network

networks:
    garage-network:
        name: garage_network
        external: true
